version: '3.1'
services:
  airport-reservation-system:
    image: creditsystemapplication
    build: ./
    ports:
      - "8085:8085"
    restart: always
    depends_on:
      - postges-db
    links:
      - postges-db

  postges-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=passbetul
      - POSTGRES_USER=postgres
      - POSTGRES_DB=patika_creditsystem_system_db


