version: '3.1'
services:
  creditsystem:
    image: patikacreditsystemapplication
    build: ./
    ports:
      - "8085:8085"

  frontend:
    image: creditsystem
    build: ./
    ports:
      - "3000:4001"

    environment:
      - CHOKIDAR_USEPOLLING=true


